### ISSUE TITLE
建议选中【支援机械】增加时长提示

### ISSUE THREAD

**Issue by Yanstory** [Tsuk1ko/arknights-toolbox#17]
毕竟一星小车，拉满9小时=没了
~~哪怕它出率低~~

**Comment by Tsuk1ko** [comment]
意思是增加【支援机械】只拉一小时的提示么😂

**Comment by Yanstory** [comment]
3:50及以下就行😂超过3:50就必定没车了，3:50以内还是有希望的
~~鬼才yj怎么3:50支援机械也没有小车~~

**Comment by Tsuk1ko** [comment]
行，马上就加

反正我也觉得挺迷的，不清楚时长跟 tag 划掉概率是否有绝对的关系，就是说不知道是 1:00 出1星概率最高还是 3:50 最高
