### ISSUE TITLE
精英材料计算中没有新干员阿、年、吽

### ISSUE THREAD

**Issue by Artanis55** [Tsuk1ko/arknights-toolbox#19]
精英材料计算中还没有新干员阿、年、吽。
另外这两个网址怎么版本还不一样……一个更新日期12-11，一个更新日期1-12。

**Comment by Tsuk1ko** [comment]
之前没有是因为 Wiki 还没有，以前都是从 Wiki 爬的数据，最近因为大佬放了解包出来所以正在重写整个数据获取逻辑并且支持中英日韩服，估计今晚或明天做好，请等待一下

目前最新数据日期是 1-18，由于 PWA 的更新机制，你需要维持当前页面一段时间等待其检测并下载完更新数据才会提示你刷新页面更新，不挂代理的情况下可能速度比较慢，下一版本会增加主动检测和提示
