### ISSUE TITLE
【精英材料】页面的【需求狗粮】开关失效

### ISSUE THREAD

**Issue by hakula139** [Tsuk1ko/arknights-toolbox#21]
最新版本下，【需求狗粮】开关不会改变经验卡的权重。举例来说，当需求【提纯源岩】+【全新装置】时，开启【需求狗粮】开关，【我该刷什么图】会推荐刷 4-6 图，而非 1-7 图。

![384F2171-7F69-4106-81BE-BBD6422C9E78](https://user-images.githubusercontent.com/9496568/73120619-c547dc80-3fab-11ea-9fdc-ee25ed8eb894.png)
![7A1573CF-1481-4384-AE9E-FCD8D73C4A9A](https://user-images.githubusercontent.com/9496568/73120620-c547dc80-3fab-11ea-9f3c-b4dc52cef1f0.png)

同时可以发现 1-7 图的获得材料中不包含经验卡。

![888B9FE6-1182-4245-89AE-0CD7FF300F46](https://user-images.githubusercontent.com/9496568/73120650-d85aac80-3fab-11ea-878e-da105e429df0.png)

之前版本无此问题（猜测或许与数据来源变更有关）。

**Comment by Tsuk1ko** [comment]
是的，确实是这次大改后忘记调整这个功能了，感谢发现问题
