### ISSUE TITLE
【公开招募】页面的【高级资深干员】标签失效

### ISSUE THREAD

**Issue by hakula139** [Tsuk1ko/arknights-toolbox#22]
![117EBCDE-A499-4D51-A07E-4E4AFCF50C26](https://user-images.githubusercontent.com/9496568/73120924-14434100-3faf-11ea-9648-be651fadeac7.png)

如图所示，左侧没有显示相关 6 星干员。其余标签无此问题，之前版本无此问题。（因为是不相关的 bug，原谅我开了两个 Issue 页面。）

**Comment by Tsuk1ko** [comment]
真是太感谢了，帮忙发现这么多问题

之前的大改实在太大了，只想着快点做完结果没测试的太仔细😂

**Comment by hakula139** [comment]
> 真是太感谢了，帮忙发现这么多问题
> 
> 之前的大改实在太大了，只想着快点做完结果没测试的太仔细😂

不客气，也感谢您能这么快解决这些问题😂 工具箱很好用，感谢您的付出！新年快乐！

**Comment by Tsuk1ko** [comment]
同乐同乐

![image](https://user-images.githubusercontent.com/24877906/73121738-44431200-3fb8-11ea-9930-d0d4eb68fe29.png)
