### ISSUE TITLE
是我打开的方式不对吗，为什么没有组合标签了

### ISSUE THREAD

**Issue by 1004452714** [Tsuk1ko/arknights-toolbox#23]
如图，
![1](https://user-images.githubusercontent.com/28773469/73263226-0db10580-420b-11ea-9810-5cea432cb034.png)

**Comment by Tsuk1ko** [comment]
@1004452714 这个bug已经修复了，等更新完重载页面即可

但同时有个提示的bug，更新完成的提示有概率会被吞，也已经修复，因此你可以试试手动刷新页面或者F12看console的提示来判断是否完成更新

**Comment by 1004452714** [comment]
感谢！已解决。好像是我网络问题，挂了代理才有更新
