### ISSUE TITLE
国际服公开招募干员数据不准确

### ISSUE THREAD

**Issue by RikkaBlue** [Tsuk1ko/arknights-toolbox#24]
![image](https://user-images.githubusercontent.com/46104879/75105470-8cecfa00-564e-11ea-8dcc-dac289e18c70.png)
在 dps 的 tag 中有夜魔，但是游戏中公开招募干员表中并没有夜魔。
![image](https://user-images.githubusercontent.com/46104879/75105487-c291e300-564e-11ea-9268-d68bbf8d18f3.png)

**Comment by Tsuk1ko** [comment]
确实，我写的时候只考虑了国服的公招，过会更新下逻辑

**Comment by RikkaBlue** [comment]
感谢。(PWA大好）

**Comment by Tsuk1ko** [comment]
@RikkaBlue 对了，如果方便的话可以下次上线的时候截几张外服的公招截图贴在这个 issue 里吗，我想准备测试开放对外服公招的 OCR 功能

**Comment by RikkaBlue** [comment]
@Tsuk1ko 
乐意至极
![image](https://user-images.githubusercontent.com/46104879/75112596-38627280-5680-11ea-9898-5c65437ff8fe.png)
![image](https://user-images.githubusercontent.com/46104879/75112623-85dedf80-5680-11ea-8dcd-14a84070c046.png)
![image](https://user-images.githubusercontent.com/46104879/75112642-aa3abc00-5680-11ea-96ee-589fcd7291f9.png)

**Comment by Tsuk1ko** [comment]
@RikkaBlue 非常感谢！
