### ISSUE TITLE
希望能够动态调节条目间的空隙让条目左右都能对齐

### ISSUE THREAD

**Issue by StarXu** [Tsuk1ko/arknights-toolbox#28]
如图 ![image](https://user-images.githubusercontent.com/39948021/77498416-8be7fc00-6e8a-11ea-8aa3-e123238c7281.png)

**Comment by Tsuk1ko** [comment]
当初设计的时候有考虑过，这样做的话当横向间隙比较大的时候看起来会很难看，所以只在移动设备屏幕宽度下会做调整

这个问题我考虑下吧，初步想法是调整块的宽度，如果你有其它建议也欢迎提出

**Comment by viewweiwu** [comment]
我刚刚提了 pr 修复了这个问题 @Tsuk1ko 
https://github.com/Tsuk1ko/arknights-toolbox/pull/32

![](https://user-gold-cdn.xitu.io/2020/4/21/1719c8de7c8270e6?w=1852&h=664&f=png&s=297417)

![](https://user-gold-cdn.xitu.io/2020/4/21/1719c980899bbebb?w=1682&h=1038&f=png&s=412178)

**Comment by Tsuk1ko** [comment]
@viewweiwu 感谢 pr，这个方法很棒，但仍有一些 bug 和细节问题，我会在完善后合入 master

**Comment by viewweiwu** [comment]
@Tsuk1ko 可以加我的 wx:     viewweiwu

**Comment by Tsuk1ko** [comment]
@viewweiwu 因为里面有些奇怪的逻辑，我自己比较熟所以自己改就行了，谢了
