### ISSUE TITLE
公开招募界面个别标签显示出错

### ISSUE THREAD

**Issue by hakula139** [Tsuk1ko/arknights-toolbox#3]
![6D272A73-3A36-4E1E-898F-17D34F75D084](https://user-images.githubusercontent.com/9496568/63626884-a24d8100-c637-11e9-9757-2962f8043537.png)

今天刚出现的，可能哪个地方改炸了（

**Comment by Tsuk1ko** [comment]
昨天更了一下数据，没检查到这块，joyme wiki 不按套路出牌，空了一些数据导致的😂

![](https://i.loli.net/2019/08/24/O71qpG6mWratHEJ.jpg)

马上修
