### ISSUE TITLE
是否可以加一个干员列表、干员详情页面

### ISSUE THREAD

**Issue by viewweiwu** [Tsuk1ko/arknights-toolbox#37]
就像明日方舟 wiki 那样，
http://ak.mooncell.wiki/w/%E5%82%80%E5%BD%B1
数据 wiki 哪里也可以直接拿的到。
![image.png](https://i.loli.net/2020/04/28/CjcMBEtAnvls5YO.png)

**Comment by Tsuk1ko** [comment]
以前有想过，后来觉得工具箱本身定位还是工具箱，这类信息展示还是交给 wiki 吧，我也不太想放太多无帮助的文本和大图立绘进去，并且现在在公招和材料计算添加预设时都可以跳转 wiki，也算是方便查询了

唯一决定会加的只有技能描述，在材料计算添加预设时展示，反正就是漫长的咕咕了

![](https://user-images.githubusercontent.com/24877906/80441215-04842180-893d-11ea-9ba4-57edd1a755f8.gif)

**Comment by viewweiwu** [comment]
原来如此。

**Comment by viewweiwu** [comment]
因为看到技能基建筛选有点偏展示，所以想着是不是也可以加一个干员筛选什么的.
