### ISSUE TITLE
TODO: 指定合成数量

### ISSUE THREAD

**Issue by doir** [Tsuk1ko/arknights-toolbox#39]
具体如图
![20200507003909.png](https://i.loli.net/2020/05/07/HkrJeVsvZWnAaXg.png)

**Comment by Tsuk1ko** [comment]
模拟合成的时候有计算顺序，合成五水研磨石的材料被改量装置用了，就是说仍需小括号里的数字表示可以合的数量，大于 0 才显示并显示合成按钮

想想的话确实可以改成只要能合就给和，不过并不能同时算进小括号里，不然继续向上级合成就会出问题

**Comment by doir** [comment]
使用体验上，感觉分开会比较好一些？
仍需小括号还是按照优先顺序计算，但是合成按钮是单独计算，能合成就显示。

其实如果这样的话，感觉如果支持单个合成，或者指定合成数量会更好一些？

**Comment by Tsuk1ko** [comment]
是，我目前就是这样改的，一会就更

指定合成数量后续再做

**Comment by doir** [comment]
辛苦啦~

**Comment by Tsuk1ko** [comment]
已经实装了，加了个合成一次的按钮
