### ISSUE TITLE
保底词条需要更新

### ISSUE THREAD

**Issue by tom0000tom** [Tsuk1ko/arknights-toolbox#43]
一下词条组合以没有保底4星了：
防护+治疗：会出现三星重装 斑点
群攻+生存：会出现三星近卫 泡普卡

**Comment by Tsuk1ko** [comment]
保底词条计算是根据现有数据自动计算的，你在用的工具箱可能仍是旧版

这是最新的数据版本：

![image](https://user-images.githubusercontent.com/24877906/82115351-dc961a00-9794-11ea-9071-df045c00eac3.png)

你需要打开工具箱页面等待一段时间，直到提示发现更新和更新完成，点击重载
