### ISSUE TITLE
素材按仓库排序

### ISSUE THREAD

**Issue by RunningMelos** [Tsuk1ko/arknights-toolbox#5]
你好，想请问下是否能让素材按仓库顺序排序呢，这样在填写素材的时候会方便些，此外未来会加入仓库ocr吗（ ~~我在想桃子~~
以上，谢谢啦

**Comment by Tsuk1ko** [comment]
即使仿照仓库排序开做，也会因为没有某个材料而产生错位吧

我理解这个问题核心应该是如何快速找到要输入的材料并快速输入数据，我的想法是加一个按拼音首字母筛选的功能，并且可以加上便捷操作，例如输入`tz 5`回车就可以直接把糖组的已有设为5

至于ocr应该是没有了，我自己没有这个能力，一只黑猫的工具箱有，但我也不好厚着脸皮向他们要接口使用权🌚

https://aktools.graueneko.xyz/autodetect

**Comment by RunningMelos** [comment]
我想的是仓库顺序排列的话，在分屏或者截图后对照着添加数目时能够快速的填写，哪怕仓库没有相应的素材也能很快到下一个素材，对照按稀有度的话就要不停的滑动去找相应等级的素材数量，~~鱼的记忆~~。至于快速输入也是个很不错的想法，不过我想可能有些刀客塔可能会记忆成大石头，紫石头，蓝石头这样（捂脸。另外OCR的话有没有都ok啦，我觉得本来就已经足够好了🤪

**Comment by Tsuk1ko** [comment]
😆主要是仓库是竖向排列的，想要仿照的话不好实现，太花功夫了，而且顺序也是个迷

另外找素材比较困难这个我也思考了一下，我感觉是素材板块太大，同屏素材太少，导致需要经常翻，可以考虑出个简洁模式开关，只保留素材icon和输入框🤔这样应该会更好找

**Comment by RunningMelos** [comment]
![image](https://user-images.githubusercontent.com/44662261/65145383-0d7a4f80-da4c-11e9-9db7-ddf8da479f7f.png)
游戏内的现有素材是以如图的从左至右再从上至下的。也就是
```
一个等级：D32钢 、双极纳米片 、聚合剂
两个等级：白马醇&下级材料 、三水锰矿&下级材料 、五水研磨石&下级材料 、RMA70-40&下级材料
四个等级：提纯源岩&下级材料 、改量装置&下级材料 、聚酸酯块&下级材料 、糖聚块&下级材料 、异铁块&下级材料 、酮阵列&下级材料 
```

因为这个顺序是固定不变的，至于仓库竖向排列的话，以现在的布局来看只要以这个顺序排列就可以了。甚至现在的按稀有度分区块也可以以下级的材料数量来分，比如：
```
单级材料：D32钢 、双极纳米片 、聚合剂
两级材料： ···
四级材料： ···
```
这样的话在我的想象中应该会快一些。因为我不太懂程序这块，这可能是我想当然的想法，所以如果实现起来很麻烦而给你带来困扰的话先道个歉🙇（捂脸。

**Comment by Tsuk1ko** [comment]
没事，原来是这样的🤔

那我就在简洁模式下按照这个顺序排列吧

**Comment by RunningMelos** [comment]
好嘞，辛苦啦！

**Comment by RunningMelos** [comment]
啊对了，我看算法应该有参考`ArkPlanner`(?)，那么会考虑增加的 `考虑合成副产物` / `需求龙门币` / `需求狗粮`的选项吗，这样就能 **一杯茶一包烟，1-7里住一天.jpg** 了XD。

**Comment by Tsuk1ko** [comment]
副产物不确定而且概率不高，不会考虑（就当下一次材料所需材料又少了一点好啦，也不可能真的指望刚好出一个副产物把材料填齐吧

至于刷图会掉龙门币和狗粮，合成需要龙门币的这个问题，是可以计算，同时将龙门币转化成理智用于线性规划条件

但刷图归刷图，就不和干员升级计算整合了，毕竟每个人的情况都不同

**Comment by RunningMelos** [comment]
龙门币和狗粮一般来说是理智消耗的12倍，这在 [Arkplaner](https://github.com/ycremar/ArkPlanner/blob/c1c5e00acb8f60c6d3ffabaa8a5ab52b62cdb000/MaterialPlanning.py#L88-111) 有一定的体现。

不过 '需求龙门币' 我看过开启和关闭都很接近，但 '需求狗粮' 有一定的差别，以我现在专三的需求来看：

 | 需求狗粮 | 预期理智 | 作战次数| 狗粮掉落 |
 | :---: | :---: | :---: | :---: |
 | 是 | 10956 | 796 | 86147 |
 | 否 | 10838 | 572 | 0 |

约等于差了 12 把 LS-5 (360理智) 的样子，不过因为多的作战次数几乎都是走 1-7，所以精污倒是有点（🤦‍♂

**Comment by Tsuk1ko** [comment]
我理解“需求狗粮”开启就是在理智“赚”的情况下去刷掉更多狗粮的副本？🤔

**Comment by RunningMelos** [comment]
差不多是这样？主要是相比 4-4 追梦来说我会更倾向于 1-7 ，因为掉落相对更加稳定（当然大家会有各自的看法），反正都是看录像，为什么不顺手薅点狗粮呢，算下来横竖都不亏。（当然因为要刷的太多就开按键精灵刷了，所以时间成本可以不算在里面）

**Comment by Tsuk1ko** [comment]
> 没事，原来是这样的🤔
> 
> 那我就在简洁模式下按照这个顺序排列吧

实装了，感觉如何 @RunningMelos

**Comment by RunningMelos** [comment]
感觉很棒！谢谢啦 🙏

**Comment by Tsuk1ko** [comment]
@RunningMelos 需求狗粮的功能也加上了，然后规划结果里增加了龙门币和狗粮的统计

试了下确实每把获得的 EXP 和龙门币都是理智消耗的 12 倍，狗粮的话有些本掉有些不掉，这应该也是“需求龙门币”对结果几乎没有影响而“需求狗粮”有影响的原因吧😂

**Comment by RunningMelos** [comment]
收到收到~体验绝妙！

对于需求的话，差不多是这样的，至于龙门币的话我记得好像是有个别关卡特殊（常规掉落为龙门币），除非那几关的副产物需求很大，才会有点影响。狗粮需求我想最大的影响就是1-7了，一方面土块需求旺盛，一方面掉落又稳定。

**Comment by Tsuk1ko** [comment]
那行，摸了一个月的 issue 完成了🤣
