### ISSUE TITLE
有没有考虑做个信赖计算器

### ISSUE THREAD

**Issue by Yanstory** [Tsuk1ko/arknights-toolbox#59]
如题，[PRTS上已经有了信赖计算列表](http://ak.mooncell.wiki/id/1319#.E5.B9.B2.E5.91.98.E4.BF.A1.E8.B5.96)，有没有考虑像经验计算器那样做一个信赖计算器呢？

**Comment by Tsuk1ko** [comment]
具体用途是什么呢

**Comment by Yanstory** [comment]
周回本的时候会考虑带上刷信赖的队伍，然后就不知道到底刷多久才能刷完，就想着既然这种需求还算是比较多的，可以考虑一下？

**Comment by Tsuk1ko** [comment]
感觉信赖没有什么计算的成分，完全是看表，没有做的必要……

列个 excel 可能都好算一点？🤔
