### ISSUE TITLE
台服活动

### ISSUE THREAD

**Issue by nakaharachuya** [Tsuk1ko/arknights-toolbox#64]
台服活动骑兵与猎人在7月23号更新了

**Comment by Tsuk1ko** [comment]
工具箱数据是根据解包 [Kengxxiao/ArknightsGameData](https://github.com/Kengxxiao/ArknightsGameData) 更新的，目前那边没更新我这里也没有什么办法……

**Comment by Tsuk1ko** [comment]
话说我看了下目前台服解包里有斯卡蒂和格拉尼的数据，还有哪里缺？
