### ISSUE TITLE
幹員升級頁面選擇問題

### ISSUE THREAD

**Issue by b0331017** [Tsuk1ko/arknights-toolbox#67]
![FFA147D1-6D31-4852-9D4D-CD11A485ED55](https://user-images.githubusercontent.com/40166953/89100678-86e41c00-d42b-11ea-9777-1ab7f07661c2.png)

手機版在幹員升級頁面中若原先選擇1-5星，會如附圖中無法選擇到6星的問題，若原先就選擇6星則無問題

**Comment by Tsuk1ko** [comment]
感谢报告，已修复
