### ISSUE TITLE
材料计算功能，PC端选择干员时，UI有问题。

### ISSUE THREAD

**Issue by daijunchen** [Tsuk1ko/arknights-toolbox#68]
PC端，已经开启了disableCache，选择干员出现的悬浮窗的高度不对。
拖动窗口大小让ui重新布局后可以暂时恢复正常。
![UI错误](https://user-images.githubusercontent.com/34501634/89116604-99f8f980-d4c8-11ea-863b-42d61f589785.png)

**Comment by Tsuk1ko** [comment]
感谢报告，已修复，等个一两分钟刷新下更新即可
